### ISSUE TITLE
Error running OpenDA; problem with DuD

### ISSUE THREAD

**Issue by phoenicus1** [hydpy-dev/OpenDA#10]
When I'm running the _oda_run_batch_ in the command line, I get the following error. Do you have an idea how to fix this?
I'm using Python 3.8 in a virtual environmnet with the latest HydPy-Version + OpenDA 2.4.5.

Thanks in advance!

What is the difference between _org.hydpy.openda.HydPyModelFactory_ and _org.hydpy.openda.HydPyStochModelFactory_?

```
(hydpyV2) C:\GIT\OpenDA_pycharme\demos\openda_projects\DUD>set PATH=C:\openda\bin;%PATH

(hydpyV2) C:\GIT\OpenDA_pycharme\demos\openda_projects\DUD>oda_run_batch main.oda
OPENDADIR set to C:\openda\bin\
"System set to win32_ifort"
Application initializing
Application initializing
OpenDA version 2.4.5.-1 May 27 2020
seriesTrees[0]<?xml version="1.0"?>
<timeSeries id="dill_nodes_sim_series" status="use" standardDeviation="2.0">data/dill.discharge.noos</timeSeries>

status=use
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Could not create instance for org.hydpy.openda.HydPyStochModelFactory: org.hydpy.openda.HydPyStochModelFactory
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:357)
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:342)
        at org.openda.application.ApplicationRunnerSingleThreaded.initialize(ApplicationRunnerSingleThreaded.java:38)
        at org.openda.application.OpenDaApplication.runApplicationBatch(OpenDaApplication.java:119)
        at org.openda.application.OpenDaApplication.main(OpenDaApplication.java:108)
Caused by: java.lang.RuntimeException: Could not create instance for org.hydpy.openda.HydPyStochModelFactory: org.hydpy.openda.HydPyStochModelFactory
        at org.openda.utils.ObjectSupport.createNewInstance(ObjectSupport.java:49)
        at org.openda.utils.ObjectSupport.createConfigurable(ObjectSupport.java:79)
        at org.openda.utils.ObjectSupport.createConfigurable(ObjectSupport.java:62)
        at org.openda.application.ApplicationRunner.createStochModelFactory(ApplicationRunner.java:480)
        at org.openda.application.ApplicationRunner.createApplicationComponents(ApplicationRunner.java:380)
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:351)
        ... 4 more
Error running OpenDA - please check the error messages
Drücken Sie eine beliebige Taste . . .
```

**Comment by tyralla** [comment]
Hi!  HydPy, OpenDA, and the Adapter are under active development.  So, we should first check if the versions of HydPy, OpenDA, the adapter, and the demo project fit.   Are the following assumptions correct?

- HydPy: 4.0.1
- OpenDA: 2.4.5
- Adapter: 0.11.0
- Demo: 0.11.0

**Comment by GernotBelger** [comment]
The difference between org.hydpy.openda.HydPyModelFactory and org.hydpy.openda.HydPyStochModelFactory is approximatively the same as the difference between org.openda.blackbox.wrapper.BBModelFactory and org.openda.blackbox.wrapper.BBStochModelFactory.

Both HydPy implementations are wrappers around the resp. BB implementations.
The BBStochModelFactory is typically used as primary stoch model to be used within the main.oda file, whereas the BBModelFactory  wraps the underlying 'real' model and is itself referenced by the BBStochModelFactory  configuration (model.xml in our examples).

***However***: the HydPyStochModelFactory  was recently dropped as there is nor more need for it due to a recent rework of the code base. Instead replace it (in the main.oda file) with  org.openda.blackbox.wrapper.BBStochModelFactory.

For some reason, this change did not make it into the last release / github-commit for most demo projects except EnKF. 
The main.od files of the demo projects are now updated in the last version in github and will get into the next release.

The EnKF demo project should work however in the last release, as the change was done properly there.

**Comment by phoenicus1** [comment]
Thank you for the fast response and your helpful messages.

> Hi! HydPy, OpenDA, and the Adapter are under active development. So, we should first check if the versions of HydPy, OpenDA, the adapter, and the demo project fit. Are the following assumptions correct?
> 
>     HydPy: 4.0.1
>     OpenDA: 2.4.5
>     Adapter: 0.11.0
>     Demo: 0.11.0

These assumptions are correct. I'm using these versions.

```
(hydpyV2) C:\GIT\OpenDA_pycharme\demos\openda_projects\DUD>oda_run_batch main.oda
OPENDADIR set to C:\openda\bin\
"System set to win32_ifort"
Application initializing
Application initializing
OpenDA version 2.4.5.-1 May 27 2020
seriesTrees[0]<?xml version="1.0"?>
<timeSeries id="dill_nodes_sim_series" status="use" standardDeviation="2.0">data/dill.discharge.noos</timeSeries>

status=use
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Could not create instance for org.hydpy.openda.HydPyModelFactory: org.hydpy.openda.HydPyModelFactory
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:357)
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:342)
        at org.openda.application.ApplicationRunnerSingleThreaded.initialize(ApplicationRunnerSingleThreaded.java:38)
        at org.openda.application.OpenDaApplication.runApplicationBatch(OpenDaApplication.java:119)
        at org.openda.application.OpenDaApplication.main(OpenDaApplication.java:108)
Caused by: java.lang.RuntimeException: Could not create instance for org.hydpy.openda.HydPyModelFactory: org.hydpy.openda.HydPyModelFactory
        at org.openda.utils.ObjectSupport.createNewInstance(ObjectSupport.java:49)
        at org.openda.blackbox.wrapper.BBStochModelFactory.initialize(BBStochModelFactory.java:70)
        at org.openda.utils.ObjectSupport.createConfigurable(ObjectSupport.java:82)
        at org.openda.utils.ObjectSupport.createConfigurable(ObjectSupport.java:62)
        at org.openda.application.ApplicationRunner.createStochModelFactory(ApplicationRunner.java:480)
        at org.openda.application.ApplicationRunner.createApplicationComponents(ApplicationRunner.java:380)
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:351)
        ... 4 more
Error running OpenDA - please check the error messages
Drücken Sie eine beliebige Taste . . .
```

After changing the line of code in the main.oda file of the DuD example, I'm getting now a slightly different error message.

If It is exactly the same error I'm getting while starting the EnKF-Example.

**Comment by tyralla** [comment]
Unfortunately, we forgot to mark 0.11.0 as a pre-release.  Sorry for the inconvenience.

However, if you prefer a recent version of the HydPy-OpenDA-Adapter, try the following steps:

1.  Install the latest version of OpenDA (I still work with 3.0.0, but 3.0.4 should work as well).
2.  Insert the 0.11.0 binaries of the adapter into its `bin` directory as usual.
3.  Check out the HydPy branch [openda/v0.11.0](https://github.com/hydpy-dev/hydpy/tree/openda/v0.11.0)
4.  [Manually compile HydPy and install it into the relevant environment](https://hydpy-dev.github.io/hydpy/master/install.html#selecting-a-hydpy-distribution)
5.  Set the "logMode" in all "hydpy.properties" files to "console".

Then, all tests of the current adapter documentation should pass.

There will be more changes to HydPy and the adapter in the next few weeks.  Once everything is settled, we will release compatible binaries and update the documentation.  Until then, do not hesitate to contact us (and eventually re-open this issue) if you encounter further problems.

**Comment by phoenicus1** [comment]
```

C:\Users\Weier>c:/openDA/3_0_0/bin/oda_run_batch C:/GIT/OpenDA_pycharme/demos/openda_projects/DUD/main.oda
OPENDADIR set to c:\openda\3_0_0\bin\
"System set to win32_ifort"
=========================================================================
Starting "java org.openda.application.OpenDaApplication C:/GIT/OpenDA_pycharme/demos/openda_projects/DUD/main.oda > openda_logfile.txt"
org.hydpy.openda.server.HydPyServerException: HydPyServer 0 - 8080: failed to start process
        at org.hydpy.openda.server.HydPyServerStarter.startProcess(HydPyServerStarter.java:224)
        at org.hydpy.openda.server.HydPyServerStarter.doStart(HydPyServerStarter.java:103)
        at org.hydpy.openda.server.HydPyUtils$2.call(HydPyUtils.java:314)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "C:\venv\hydpy_temp\Scripts" (in directory "C:\GIT\OpenDA_pycharme\demos\hydpy_projects"): CreateProcess error=5, Zugriff verweigert
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.hydpy.openda.server.HydPyServerStarter.startProcess(HydPyServerStarter.java:220)
        ... 6 more
Caused by: java.io.IOException: CreateProcess error=5, Zugriff verweigert
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 7 more
org.hydpy.openda.server.HydPyServerException: HydPyServer 0 - 8080: failed to start process
        at org.hydpy.openda.server.HydPyServerStarter.startProcess(HydPyServerStarter.java:224)
        at org.hydpy.openda.server.HydPyServerStarter.doStart(HydPyServerStarter.java:103)
        at org.hydpy.openda.server.HydPyUtils$2.call(HydPyUtils.java:314)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "C:\venv\hydpy_temp\Scripts" (in directory "C:\GIT\OpenDA_pycharme\demos\hydpy_projects"): CreateProcess error=5, Zugriff verweigert
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.hydpy.openda.server.HydPyServerStarter.startProcess(HydPyServerStarter.java:220)
        ... 6 more
Caused by: java.io.IOException: CreateProcess error=5, Zugriff verweigert
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 7 more
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed to start HydPy Server
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:356)
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:341)
        at org.openda.application.ApplicationRunnerSingleThreaded.initialize(ApplicationRunnerSingleThreaded.java:38)
        at org.openda.application.OpenDaApplication.runApplicationBatch(OpenDaApplication.java:113)
        at org.openda.application.OpenDaApplication.main(OpenDaApplication.java:102)
Caused by: java.lang.RuntimeException: Failed to start HydPy Server
        at org.hydpy.openda.server.HydPyServerManager.getOrCreateServer(HydPyServerManager.java:177)
        at org.hydpy.openda.server.HydPyServerManager.createInstance(HydPyServerManager.java:147)
        at org.hydpy.openda.server.HydPyServerManager.getOrCreateInstance(HydPyServerManager.java:138)
        at org.hydpy.openda.HydPyModelFactory.createFactory(HydPyModelFactory.java:111)
        at org.hydpy.openda.HydPyModelFactory.getFactory(HydPyModelFactory.java:102)
        at org.hydpy.openda.HydPyModelFactory.getInstance(HydPyModelFactory.java:247)
        at org.openda.blackbox.wrapper.BBStochModelFactory.getInstance(BBStochModelFactory.java:146)
        at org.openda.algorithms.BaseDud.setStochComponents(BaseDud.java:123)
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:351)
        ... 4 more
Caused by: org.hydpy.openda.server.HydPyServerException: HydPyServer 0 - 8080: failed to start process
        at org.hydpy.openda.server.HydPyServerStarter.startProcess(HydPyServerStarter.java:224)
        at org.hydpy.openda.server.HydPyServerStarter.doStart(HydPyServerStarter.java:103)
        at org.hydpy.openda.server.HydPyUtils$2.call(HydPyUtils.java:314)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "C:\venv\hydpy_temp\Scripts" (in directory "C:\GIT\OpenDA_pycharme\demos\hydpy_projects"): CreateProcess error=5, Zugriff verweigert
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.hydpy.openda.server.HydPyServerStarter.startProcess(HydPyServerStarter.java:220)
        ... 6 more
Caused by: java.io.IOException: CreateProcess error=5, Zugriff verweigert
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 7 more
org.hydpy.openda.server.HydPyServerException: HydPyServer 0 - 8080: failed to start process
        at org.hydpy.openda.server.HydPyServerStarter.startProcess(HydPyServerStarter.java:224)
        at org.hydpy.openda.server.HydPyServerStarter.doStart(HydPyServerStarter.java:103)
        at org.hydpy.openda.server.HydPyUtils$2.call(HydPyUtils.java:314)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "C:\venv\hydpy_temp\Scripts" (in directory "C:\GIT\OpenDA_pycharme\demos\hydpy_projects"): CreateProcess error=5, Zugriff verweigert
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.hydpy.openda.server.HydPyServerStarter.startProcess(HydPyServerStarter.java:220)
        ... 6 more
Caused by: java.io.IOException: CreateProcess error=5, Zugriff verweigert
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 7 more
Error running OpenDA - please check the error messages
Drücken Sie eine beliebige Taste . . .
```

**Comment by phoenicus1** [comment]
After extracting the proper .jar-files of the modelwraper into the binaries-folder and editing the environment variables (https://github.com/hydpy-dev/OpenDA/tree/master/extensions/HydPyOpenDABBModelWrapper) it works now smoothly.

> Depending on your HyPy and Python installation two additional system environment variables can be set:
>     HYD_PY_PYTHON_EXE: Path to the python.exe (defaults to 'python.exe')
>     HYD_PY_SCRIPT_PATH: Path to the hyd.py script. (defaults to 'hyd.py')

Thanks a lot for the phone support.
